version: "3.1"
services:
  mongodb:
    image: mongo:3.6.8
    volumes:
      - ./database:/data/db
    ports:
      - "127.0.0.1:27017:27017"
    command: mongod --bind_ip=0.0.0.0 --logpath=/dev/null
  # Remove below comments to use this container. "adminMongo is a Web based user interface (GUI) to handle all your MongoDB connections/databases needs."
  #
  #adminmongo:
  #  image: mrvautin/adminmongo
  #  links:
  #    - mongodb
  #  tty: true
  #  ports:
  #    - "127.0.0.1:1234:1234"
  #  environment:
  #    - CONN_NAME=zenbot_mongodb
  #    - DB_HOST=mongodb
  #    - DB_PORT=27017
  #    - HOST=0.0.0.0
  #  command: "npm start"
